// Mocks generated by Mockito 5.4.4 from annotations
// in doc_scanner/test/core/services/audit_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:doc_scanner/core/domain/entities/audit_event.dart' as _i6;
import 'package:doc_scanner/core/domain/entities/backup_metadata.dart' as _i7;
import 'package:doc_scanner/core/domain/entities/document.dart' as _i5;
import 'package:doc_scanner/core/services/database_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i3.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> getDatabase(String? password) => (super.noSuchMethod(
        Invocation.method(
          #getDatabase,
          [password],
        ),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #getDatabase,
            [password],
          ),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> insertDocument(_i5.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocument,
          [document],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDocument(_i5.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Document?> getDocument(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
        ),
        returnValue: _i4.Future<_i5.Document?>.value(),
      ) as _i4.Future<_i5.Document?>);

  @override
  _i4.Future<List<_i5.Document>> getDocuments({
    int? limit = 50,
    int? offset = 0,
    String? documentType,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {
            #limit: limit,
            #offset: offset,
            #documentType: documentType,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i4.Future<List<_i5.Document>>.value(<_i5.Document>[]),
      ) as _i4.Future<List<_i5.Document>>);

  @override
  _i4.Future<List<_i5.Document>> searchDocuments({
    required String? query,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [],
          {
            #query: query,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i5.Document>>.value(<_i5.Document>[]),
      ) as _i4.Future<List<_i5.Document>>);

  @override
  _i4.Future<void> deleteDocument(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertAuditEvent(_i6.AuditEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditEvent,
          [event],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.AuditEvent>> getAuditEvents({
    _i6.AuditEventType? eventType,
    String? documentId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditEvents,
          [],
          {
            #eventType: eventType,
            #documentId: documentId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i4.Future<List<_i6.AuditEvent>>.value(<_i6.AuditEvent>[]),
      ) as _i4.Future<List<_i6.AuditEvent>>);

  @override
  _i4.Future<void> insertBackupMetadata(_i7.BackupMetadata? metadata) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertBackupMetadata,
          [metadata],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.BackupMetadata>> getBackupMetadata({
    _i7.CloudProvider? provider,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackupMetadata,
          [],
          {
            #provider: provider,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i7.BackupMetadata>>.value(<_i7.BackupMetadata>[]),
      ) as _i4.Future<List<_i7.BackupMetadata>>);

  @override
  _i4.Future<int> getDocumentCount({bool? includeDeleted = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
