// Mocks generated by Mockito 5.4.4 from annotations
// in doc_scanner/test/core/services/backup_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i10;

import 'package:doc_scanner/core/domain/entities/audit_event.dart' as _i7;
import 'package:doc_scanner/core/domain/entities/backup_metadata.dart' as _i8;
import 'package:doc_scanner/core/domain/entities/document.dart' as _i6;
import 'package:doc_scanner/core/services/audit_service.dart' as _i12;
import 'package:doc_scanner/core/services/cloud_storage_gateway.dart' as _i3;
import 'package:doc_scanner/core/services/database_service.dart' as _i4;
import 'package:doc_scanner/core/services/encryption_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCloudFileMetadata_1 extends _i1.SmartFake
    implements _i3.CloudFileMetadata {
  _FakeCloudFileMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseService extends _i1.Mock implements _i4.DatabaseService {
  MockDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Database> getDatabase(String? password) => (super.noSuchMethod(
        Invocation.method(
          #getDatabase,
          [password],
        ),
        returnValue: _i5.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.method(
            #getDatabase,
            [password],
          ),
        )),
      ) as _i5.Future<_i2.Database>);

  @override
  _i5.Future<void> insertDocument(_i6.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertDocument,
          [document],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateDocument(_i6.Document? document) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDocument,
          [document],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.Document?> getDocument(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getDocument,
          [id],
        ),
        returnValue: _i5.Future<_i6.Document?>.value(),
      ) as _i5.Future<_i6.Document?>);

  @override
  _i5.Future<List<_i6.Document>> getDocuments({
    int? limit = 50,
    int? offset = 0,
    String? documentType,
    bool? includeDeleted = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocuments,
          [],
          {
            #limit: limit,
            #offset: offset,
            #documentType: documentType,
            #includeDeleted: includeDeleted,
          },
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<List<_i6.Document>> searchDocuments({
    required String? query,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchDocuments,
          [],
          {
            #query: query,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i6.Document>>.value(<_i6.Document>[]),
      ) as _i5.Future<List<_i6.Document>>);

  @override
  _i5.Future<void> deleteDocument(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteDocument,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> insertAuditEvent(_i7.AuditEvent? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertAuditEvent,
          [event],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.AuditEvent>> getAuditEvents({
    _i7.AuditEventType? eventType,
    String? documentId,
    DateTime? startDate,
    DateTime? endDate,
    int? limit = 100,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAuditEvents,
          [],
          {
            #eventType: eventType,
            #documentId: documentId,
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
            #offset: offset,
          },
        ),
        returnValue: _i5.Future<List<_i7.AuditEvent>>.value(<_i7.AuditEvent>[]),
      ) as _i5.Future<List<_i7.AuditEvent>>);

  @override
  _i5.Future<void> insertBackupMetadata(_i8.BackupMetadata? metadata) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertBackupMetadata,
          [metadata],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.BackupMetadata>> getBackupMetadata({
    _i8.CloudProvider? provider,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBackupMetadata,
          [],
          {
            #provider: provider,
            #limit: limit,
          },
        ),
        returnValue:
            _i5.Future<List<_i8.BackupMetadata>>.value(<_i8.BackupMetadata>[]),
      ) as _i5.Future<List<_i8.BackupMetadata>>);

  @override
  _i5.Future<int> getDocumentCount({bool? includeDeleted = false}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentCount,
          [],
          {#includeDeleted: includeDeleted},
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> optimize() => (super.noSuchMethod(
        Invocation.method(
          #optimize,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [EncryptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEncryptionService extends _i1.Mock implements _i9.EncryptionService {
  MockEncryptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Uint8List deriveKey({
    required String? password,
    required _i10.Uint8List? salt,
    int? iterations = 100000,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveKey,
          [],
          {
            #password: password,
            #salt: salt,
            #iterations: iterations,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List generateSalt() => (super.noSuchMethod(
        Invocation.method(
          #generateSalt,
          [],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List generateIV() => (super.noSuchMethod(
        Invocation.method(
          #generateIV,
          [],
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List encryptBytes({
    required _i10.Uint8List? plaintext,
    required _i10.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptBytes,
          [],
          {
            #plaintext: plaintext,
            #key: key,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List decryptBytes({
    required _i10.Uint8List? ciphertext,
    required _i10.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptBytes,
          [],
          {
            #ciphertext: ciphertext,
            #key: key,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  String encryptString({
    required String? plaintext,
    required _i10.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #encryptString,
          [],
          {
            #plaintext: plaintext,
            #key: key,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #encryptString,
            [],
            {
              #plaintext: plaintext,
              #key: key,
            },
          ),
        ),
      ) as String);

  @override
  String decryptString({
    required String? ciphertext,
    required _i10.Uint8List? key,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #decryptString,
          [],
          {
            #ciphertext: ciphertext,
            #key: key,
          },
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #decryptString,
            [],
            {
              #ciphertext: ciphertext,
              #key: key,
            },
          ),
        ),
      ) as String);

  @override
  String computeChecksum(_i10.Uint8List? data) => (super.noSuchMethod(
        Invocation.method(
          #computeChecksum,
          [data],
        ),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.method(
            #computeChecksum,
            [data],
          ),
        ),
      ) as String);

  @override
  _i10.Uint8List deriveDEK({
    required _i10.Uint8List? masterKey,
    required String? context,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveDEK,
          [],
          {
            #masterKey: masterKey,
            #context: context,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  _i10.Uint8List deriveBEK({
    required String? password,
    required _i10.Uint8List? salt,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deriveBEK,
          [],
          {
            #password: password,
            #salt: salt,
          },
        ),
        returnValue: _i10.Uint8List(0),
      ) as _i10.Uint8List);

  @override
  bool isValidKey(_i10.Uint8List? key) => (super.noSuchMethod(
        Invocation.method(
          #isValidKey,
          [key],
        ),
        returnValue: false,
      ) as bool);

  @override
  void wipeKey(_i10.Uint8List? key) => super.noSuchMethod(
        Invocation.method(
          #wipeKey,
          [key],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AuditService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuditService extends _i1.Mock implements _i12.AuditService {
  MockAuditService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> logDocumentCreated({
    required String? documentId,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDocumentCreated,
          [],
          {
            #documentId: documentId,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logDocumentViewed({
    required String? documentId,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDocumentViewed,
          [],
          {
            #documentId: documentId,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logDocumentUpdated({
    required String? documentId,
    Map<String, dynamic>? changes,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDocumentUpdated,
          [],
          {
            #documentId: documentId,
            #changes: changes,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logDocumentDeleted({
    required String? documentId,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDocumentDeleted,
          [],
          {
            #documentId: documentId,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logSearchPerformed({
    required String? query,
    required int? resultCount,
    Map<String, dynamic>? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSearchPerformed,
          [],
          {
            #query: query,
            #resultCount: resultCount,
            #filters: filters,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logAuthenticationSuccess({required String? method}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAuthenticationSuccess,
          [],
          {#method: method},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logAuthenticationFailure({
    required String? method,
    required String? reason,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logAuthenticationFailure,
          [],
          {
            #method: method,
            #reason: reason,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logBackupExported({
    required String? provider,
    required int? documentCount,
    required int? sizeBytes,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBackupExported,
          [],
          {
            #provider: provider,
            #documentCount: documentCount,
            #sizeBytes: sizeBytes,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logBackupRestored({
    required String? provider,
    required int? documentCount,
    Map<String, dynamic>? additionalData,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logBackupRestored,
          [],
          {
            #provider: provider,
            #documentCount: documentCount,
            #additionalData: additionalData,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logDecryptionError({
    String? documentId,
    required String? errorMessage,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logDecryptionError,
          [],
          {
            #documentId: documentId,
            #errorMessage: errorMessage,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logKeyAccess({
    required String? keyType,
    required String? operation,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #logKeyAccess,
          [],
          {
            #keyType: keyType,
            #operation: operation,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> logSettingsChanged(
          {required Map<String, dynamic>? changes}) =>
      (super.noSuchMethod(
        Invocation.method(
          #logSettingsChanged,
          [],
          {#changes: changes},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<List<_i7.AuditEvent>> getDocumentAuditTrail(String? documentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDocumentAuditTrail,
          [documentId],
        ),
        returnValue: _i5.Future<List<_i7.AuditEvent>>.value(<_i7.AuditEvent>[]),
      ) as _i5.Future<List<_i7.AuditEvent>>);

  @override
  _i5.Future<List<_i7.AuditEvent>> getEventsByType(
          _i7.AuditEventType? eventType) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByType,
          [eventType],
        ),
        returnValue: _i5.Future<List<_i7.AuditEvent>>.value(<_i7.AuditEvent>[]),
      ) as _i5.Future<List<_i7.AuditEvent>>);

  @override
  _i5.Future<List<_i7.AuditEvent>> getEventsByDateRange({
    required DateTime? startDate,
    required DateTime? endDate,
    int? limit = 100,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventsByDateRange,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
            #limit: limit,
          },
        ),
        returnValue: _i5.Future<List<_i7.AuditEvent>>.value(<_i7.AuditEvent>[]),
      ) as _i5.Future<List<_i7.AuditEvent>>);

  @override
  _i5.Future<List<_i7.AuditEvent>> getRecentEvents({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentEvents,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Future<List<_i7.AuditEvent>>.value(<_i7.AuditEvent>[]),
      ) as _i5.Future<List<_i7.AuditEvent>>);

  @override
  _i5.Future<Map<String, dynamic>> generateAuditSummary({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generateAuditSummary,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue:
            _i5.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<String> exportAuditLog({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #exportAuditLog,
          [],
          {
            #startDate: startDate,
            #endDate: endDate,
          },
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #exportAuditLog,
            [],
            {
              #startDate: startDate,
              #endDate: endDate,
            },
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [CloudStorageGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockCloudStorageGateway extends _i1.Mock
    implements _i3.CloudStorageGateway {
  MockCloudStorageGateway() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get providerName => (super.noSuchMethod(
        Invocation.getter(#providerName),
        returnValue: _i11.dummyValue<String>(
          this,
          Invocation.getter(#providerName),
        ),
      ) as String);

  @override
  _i5.Future<bool> authenticate() => (super.noSuchMethod(
        Invocation.method(
          #authenticate,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<bool> isAuthenticated() => (super.noSuchMethod(
        Invocation.method(
          #isAuthenticated,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.CloudFileMetadata> uploadFile({
    required String? localPath,
    required String? remotePath,
    _i3.UploadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadFile,
          [],
          {
            #localPath: localPath,
            #remotePath: remotePath,
            #onProgress: onProgress,
          },
        ),
        returnValue:
            _i5.Future<_i3.CloudFileMetadata>.value(_FakeCloudFileMetadata_1(
          this,
          Invocation.method(
            #uploadFile,
            [],
            {
              #localPath: localPath,
              #remotePath: remotePath,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.CloudFileMetadata>);

  @override
  _i5.Future<String> downloadFile({
    required String? remotePath,
    required String? localPath,
    _i3.DownloadProgressCallback? onProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadFile,
          [],
          {
            #remotePath: remotePath,
            #localPath: localPath,
            #onProgress: onProgress,
          },
        ),
        returnValue: _i5.Future<String>.value(_i11.dummyValue<String>(
          this,
          Invocation.method(
            #downloadFile,
            [],
            {
              #remotePath: remotePath,
              #localPath: localPath,
              #onProgress: onProgress,
            },
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i3.CloudFileMetadata>> listFiles({String? remotePath}) =>
      (super.noSuchMethod(
        Invocation.method(
          #listFiles,
          [],
          {#remotePath: remotePath},
        ),
        returnValue: _i5.Future<List<_i3.CloudFileMetadata>>.value(
            <_i3.CloudFileMetadata>[]),
      ) as _i5.Future<List<_i3.CloudFileMetadata>>);

  @override
  _i5.Future<void> deleteFile(String? remotePath) => (super.noSuchMethod(
        Invocation.method(
          #deleteFile,
          [remotePath],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.CloudFileMetadata> getFileMetadata(String? remotePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFileMetadata,
          [remotePath],
        ),
        returnValue:
            _i5.Future<_i3.CloudFileMetadata>.value(_FakeCloudFileMetadata_1(
          this,
          Invocation.method(
            #getFileMetadata,
            [remotePath],
          ),
        )),
      ) as _i5.Future<_i3.CloudFileMetadata>);

  @override
  _i5.Future<bool> fileExists(String? remotePath) => (super.noSuchMethod(
        Invocation.method(
          #fileExists,
          [remotePath],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<int?> getAvailableSpace() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableSpace,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);

  @override
  _i5.Future<int?> getUsedSpace() => (super.noSuchMethod(
        Invocation.method(
          #getUsedSpace,
          [],
        ),
        returnValue: _i5.Future<int?>.value(),
      ) as _i5.Future<int?>);
}
